apiVersion: v1
kind: PersistentVolume
metadata:
  name: gcp-test
  namespace: test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ssd
  capacity:
    storage: 10G
  persistentVolumeReclaimPolicy: Delete
  gcePersistentDisk:
    pdName: pd-name
    fsType: ext4
