apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  voting-app
spec:
  minReplicas: 4
  maxReplicas: 16
  targetCPUUtilizationPercentage: 30
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: voting-app
