apiVersion: batch/v1
kind: Job
metadata:
  name: loadtest
spec:
  template:
    spec:
      containers:
        - name: siege
          image: schoolofdevops/loadtest:v1
          command: ["siege", "--concurrent=5", "--benchmark", "--time=10m", "http://voting-services"]
      restartPolicy: Never
  completions: 2
  parallelism: 1
