apiVersion: v1
kind: Pod
metadata:
  name: http
  namespace: test
spec:
  containers:
    - name: test-http
      image: httpd
      volumeMounts:
        - name: gcpvol
          mountPath: /data
  volumes:
    - name: gcpvol
      gcePersistentDisk:
        pdName: test-gcp
