apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: uat
  name: redis
spec:
  replicas: 2
  selector:
    matchLabels:
      role: redis
      tier: back
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: redis
        role: redis
        tier: back
        version: latest
    spec:
      containers:
        - image: schoolofdevops/redis:latest
          imagePullPolicy: Always
          name: redis
          ports:
            - containerPort: 6379
              protocol: TCP
      restartPolicy: Always
      tolerations:
        - key: dedicated
          operator: Equal
          value: redis
          effect: NoExecute
