apiVersion: v1
kind: Service
metadata:
  labels:
    role: redis
    tier: back
  name: redis
  namespace: dev
spec:
  ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    app: redis

