apiVersion: v1
kind: Service
metadata:
  name: voting-services
  labels:
    role: voting-app-pod
spec:
  selector:
    version: beta
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31200
  type: NodePort

